# HomeWork 1

## numpy installation



In [5]:
# Uncomment to install
 
#pip install numpy 

### 1

![Question1](./images/1.png)

> Right Answer: `a=12.12 ; c=14.00`

In [6]:
import math

# Given values
b = 7  # Side b (opposite)
angle_ac = 30  # Angle between a and c in degrees

# Convert angle to radians since math functions use radians
angle_ac_rad = math.radians(angle_ac)

# Calculate side c using sine relation
c = b / math.sin(angle_ac_rad)

# Calculate side a using cosine relation
a = c * math.cos(angle_ac_rad)

print(f"Side a: {a} units")
print(f"Side c: {c} units")


Side a: 12.124355652982143 units
Side c: 14.000000000000002 units


### 2

![Question2](./images/2.png)

> Right Answer: `−11.1 − 21.9i`

In [7]:
import numpy as np

# Define the complex numbers
z1 = 3.0 - 5.0j
z2 = -4.2 - 0.3j

# Perform multiplication
result = z2 * np.conjugate(z1)

print(result)

(-11.100000000000001-21.9j)


### 3

![Question3](./images/3.png)

Right Answer: `[[-1  8  3]]`

In [8]:
import numpy as np

# Define matrix A
A = np.array([[-1, 3, 1],
              [5, 2, 1],
              [2, 0, 0]])

# Define vector u
u = np.array([[2],
              [1],
              [-2]])

# Calculate u transpose
u_transpose = u.T

# Perform the operation (u transpose) * A
result = np.dot(u_transpose, A)

print(result)

[[-1  8  3]]


### 4

![Question4](./images/4.png)

Right Answer: 

```

[[ 0  1  0  3]
 [ 4 -2  2  5]
 [ 6  3  5  1]
 [ 1  5  4  1]]

```

In [9]:
import numpy as np

# Given values
lambda_value = 2
B = np.array([[2, 1, 0, 3],
              [4, 0, 2, 5],
              [6, 3, 7, 1],
              [1, 5, 4, 3]])
I = np.identity(4)

# Calculating lambda times the identity matrix
lambda_I = lambda_value * I

# Subtracting lambda*I from B
result = B - lambda_I

print(result)

[[ 0.  1.  0.  3.]
 [ 4. -2.  2.  5.]
 [ 6.  3.  5.  1.]
 [ 1.  5.  4.  1.]]


### 5

![Question5](./images/5.png)

Right Answer: `True`

In [10]:
import numpy as np

# Define the matrix U
U = np.array([[-1/np.sqrt(3), np.sqrt(2/3)],
              [np.sqrt(2/3), 1/np.sqrt(3)]])

# Calculate the conjugate transpose of U
U_dagger = np.conjugate(U.T)

# Calculate the product of U_dagger and U
product = np.dot(U_dagger, U)

# Define the identity matrix of the same size
I = np.identity(2)

# Check if the product is equal to the identity matrix
is_unitary = np.allclose(product, I)

print("Is the matrix U unitary?", is_unitary)

Is the matrix U unitary? True


### 6

![Question6](./images/6.png)

Right Answer: 

```

[[ 0  0 -1 -2]
 [ 0  0 -3 -4]
 [ 1  2  0  0]
 [ 3  4  0  0]]

```

In [11]:
import numpy as np

# Define the matrices A and B
A = np.array([[0, -1], [1, 0]])
B = np.array([[1, 2], [3, 4]])

# Compute the Kronecker product
result = np.kron(A, B)

print(result)

[[ 0  0 -1 -2]
 [ 0  0 -3 -4]
 [ 1  2  0  0]
 [ 3  4  0  0]]


### 7

![Question7](./images/7.png)

Right Answer: `⟨ψ| = (i  3+i 2−2i)`

In [12]:
import numpy as np

# Define the ket
ket = np.array([-1j, 3 - 1j, 2 + 2j])

# Calculate the bra by taking the complex conjugate
bra = np.conjugate(ket)

print(bra)

[-0.+1.j  3.+1.j  2.-2.j]


### 8

![Question8](./images/8.png)

Right Answer: `−4 + 7i`

In [13]:
import numpy as np

# Define the vectors |w⟩ and |u⟩
w = np.array([3 + 2j, -2j, 1])
u = np.array([-2, 1 - 1j, 1j])

# Calculate the conjugate transpose of |w⟩
w_conjugate_transpose = np.conjugate(w)

# Calculate the inner product ⟨w|u⟩
inner_product = np.dot(w_conjugate_transpose, u)

print(inner_product)


(-4+7j)


### 9

![Question9](./images/9.png)

Right Answer: `c = B.dot(b)`

In [14]:
import numpy as np

# Define the arrays
b = np.array([1, 3])
B = np.array([[2, 2], [-6, 5]])

# Replace the commented line with the following
c = B.dot(b)

print(c)

[8 9]


### 10

![Question10](./images/10.png)

Right Answer: Postulate 3

### THE END